export default {
    UPDATE_FECHA                    : "UPDATE_FECHA",
    GET_CARTELERA                   : "GET_CARTELERA",
    GET_CARTELERA_FULFILLED         : "GET_CARTELERA_FULFILLED",

    //Próximos estrenos
    GET_PROXIMOS_ESTRENOS           : "GET_PROXIMOS_ESTRENOS",
    GET_PROXIMOS_ESTRENOS_PENDING   : "GET_PROXIMOS_ESTRENOS_PENDING",
    GET_PROXIMOS_ESTRENOS_FULFILLED : "GET_PROXIMOS_ESTRENOS_FULFILLED",
    GET_PROXIMOS_ESTRENOS_REJECTED  : "GET_PROXIMOS_ESTRENOS_REJECTED"
};