export default {
    UPDATE_FECHA            : "UPDATE_FECHA",
    GET_CARTELERA           : "GET_CARTELERA",
    GET_CARTELERA_FULFILLED : "GET_CARTELERA_FULFILLED",

    //Próximos estrenos
    GET_PROXIMOS_ESTRENOS           : "GET_PROXIMOS_ESTRENOS",
    GET_PROXIMOS_ESTRENOS_PENDING   : "GET_PROXIMOS_ESTRENOS_PENDING",
    GET_PROXIMOS_ESTRENOS_FULFILLED : "GET_PROXIMOS_ESTRENOS_FULFILLED",
    GET_PROXIMOS_ESTRENOS_REJECTED  : "GET_PROXIMOS_ESTRENOS_REJECTED",

    //Detalle película
    GET_DETALLE           : "GET_DETALLE",
    GET_DETALLE_PENDING   : "GET_DETALLE_PENDING",
    GET_DETALLE_FULFILLED : "GET_DETALLE_FULFILLED",
    GET_DETALLE_REJECTED  : "GET_DETALLE_REJECTED",

    //Actores de la película
    GET_ACTORES           : "GET_ACTORES",
    GET_ACTORES_FULFILLED : "GET_ACTORES_FULFILLED",
    GET_ACTORES_REJECTED  : "GET_ACTORES_REJECTED",
    GET_ACTORES_PENDING   : "GET_ACTORES_PENDING"
};